Add functions to convert a signature into bytes and vice versa
maidsafe/safe-nd pull request #130
Opened 2019-11-25 14:03 UTC by lionel1704

2019-11-25 17:06 UTC, lionel1704 commented
Just realized that we might not even need these functions as Serialize and Deserialize are already derived.

2019-11-25 17:59 UTC, mrcnski requested changes

2019-11-25 17:59 UTC, mrcnski commented on src/keys.rs
> +    /// Returns the Signature from it's byte represenation
Typos: should be "its" and "representation"

2019-11-25 17:59 UTC, mrcnski commented on src/keys.rs
> +    pub fn from_bytes(mut bytes: Vec<u8>) -> Result<Self> {
Can this parameter take `&[u8]` instead? It's more general because you can pass a reference to a `Vec<u8>` and it will deref. From what I've seen in the std library and the ecosystem `from_bytes` usually takes `&[u8]`. Also, does this have to be mutable?

2019-11-26 06:33 UTC, lionel1704 commented
These changes are not really required. The `Signature` type has the serialisation traits already derived.

2019-11-26 06:33 UTC, closed without merging